version: '3.8'

services:
  # Backend Transcription Server
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Development Server
  frontend:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - VITE_WEBSOCKET_URL=ws://localhost:8080
      - VITE_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional - for production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  default:
    name: transcription-network
